
package A2;

import javax.swing.*;
import java.awt.*;


public class SplashScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SplashScreen.class.getName());
     

    

    public SplashScreen() {
        
        initComponents();
        AppLib.scrSplash = this;
        

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(939, 939));
        setMinimumSize(new java.awt.Dimension(939, 939));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(939, 939));
        setResizable(false);
        setSize(new java.awt.Dimension(939, 939));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A2/pictures/wrd2.png"))); // NOI18N
        lblImage.setAlignmentY(0.0F);
        lblImage.setMaximumSize(new java.awt.Dimension(939, 939));
        lblImage.setMinimumSize(new java.awt.Dimension(939, 939));
        lblImage.setPreferredSize(new java.awt.Dimension(939, 939));
        lblImage.setRequestFocusEnabled(false);
        getContentPane().add(lblImage);
        lblImage.setBounds(0, 0, 939, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try 
        {
            
            Thread.sleep(1000);
            this.dispose();
            AppLib.scrMenu.setVisible(true);
            AppLib.scrMenu.toFront();
            AppLib.scrMenu.requestFocus();
        } 
        catch (InterruptedException e) 
        {
            e.printStackTrace();
        }
        
//        
//                   try{
//                java.awt.Image pic;
//                pic = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/" + dg.getFilename()));
//                //scale to label size
//                pic = pic.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), 2);
//                
//                lblImage.setIcon(new ImageIcon(pic));
//            }
//            catch(Exception ex)
//            {
//                System.out.println(ex.toString());
//            }
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SplashScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
